@MyEncryptionAPI_HostAddress = http://localhost:5156

### Testa kryptering
POST {{MyEncryptionAPI_HostAddress}}/api/encryption/encrypt
Content-Type: application/json

"Hello World"

### Testa dekryptering
POST {{MyEncryptionAPI_HostAddress}}/api/encryption/decrypt
Content-Type: application/json

"Khoor#Zruog"
